baseurl = "https://two-koalas.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Two Koalas"
theme = "hugo-theme-dream"

# copyright = "Swell Industries Inc."

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

   #dark mode
   defaultDark = true
   backgroundDark = "black"
   backgroundImageDark = "/me/background-dark.jpg"
   darkLinkColor = "darkseagreen"
   darkNav = true
   dark404 = true

  author = "Two Koalas"
  # description = "Two Koalas Documented Will to Survive the Pre Apocalypse"
  avatar = "/img/koalaheader.png"
  headerTitle = "Two Koalas Online Portal"
  motto = "ONE drink before bed NINE, es tut mir leid EIGHT (figures) NINE lives"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

   footerBottomText = "created by Two Koalas"

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "davidaragon97@gmail.com"
  # twitter = ""
  # facebook = ""
  instagram = "instagram.com/toohott2handel"
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

<<<<<<< HEAD
  favicon = /img/7a33c88d1bb2f3ee393ca0fb05e9332c.ico
=======
  favicon = "/img/favicon.ico"
>>>>>>> 9ec04f519b4e546be07665f536a58307517274a7

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"

  
